POST http://127.0.0.1:10000/users/123
Content-Type: application/json

{}

###

PUT http://127.0.0.1:10000/users/123
Content-Type: application/json

{}

###

PATCH http://127.0.0.1:10000/users/123
Content-Type: application/json

{}

###

DELETE http://127.0.0.1:10000/users/123
Content-Type: application/json

{}

###

GET http://127.0.0.1:10000/users/123

###
GET http://127.0.0.1:10000/users

###

